### ISSUE TITLE
[BUG] - Bad grammar in Wiki

### ISSUE THREAD

**Issue by Raymo111** [cs130-w21/6#71]
## Description
"A couple of zebra" -> "A few zebras"

## Relevant screenshots
![image](https://user-images.githubusercontent.com/34818275/112555947-925fcb00-8d9f-11eb-923d-cd7485686657.png)

**Comment by kellyckj** [comment]
It's auto-generated from ML without editing so minor mistakes are acceptable. But thanks anyway lmao

**Comment by Raymo111** [comment]
lol cool project!

**Comment by kellyckj** [comment]
thanks!
