### ISSUE TITLE
Story Page

### ISSUE THREAD

**Issue by why1998101** [cs130-w21/6#8]
## User Story
As a user, I would like to view my personal history, which is the storyline of our application.

## Detailed Description
The storyline has a separate page after the user has logged in, the page will display the most recent 20 stories. Within the page, the user will be able to delete a story.

## Acceptance Criteria
- [x] Given the user logged in to his/her account, then the application should automatically navigate to his/her story-line page
- [x] Given the user is on the story page, then the most recent 20 stories are shown
- [x] Given the user is on the story page, then he/she is able to create new stories via the CAMERA button on this page
- [x] Given a newly created story, then this story will get updated on this story page
- [x] Given the user is on this page, then he/she is able to delete a particular story

**Comment by yiyou-chen** [comment]
load more than 20 stories (all stories)
